[package]
name = "sweetbyte-rs"
version = "1.0.0"
edition = "2024"
description = "Multi-layered file encryption with error correction"
license = "MIT"
authors = ["Ilham Putra Husada <hambosto@gmail.com>"]
readme = "README.md"
keywords = ["encryption", "security", "crypto", "aes", "chacha20"]
categories = ["cryptography", "command-line-utilities"]

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.100"
argon2 = "0.5.3"
byteorder = "1.5.0"
chacha20poly1305 = "0.10.1"
clap = { version = "4.5.54", features = ["derive"] }
comfy-table = "7.2.2"
console = "0.16.2"
crossbeam-channel = "0.5.15"
dialoguer = "0.12.0"
flate2 = "1.1.8"
figlet-rs = "0.1.5"
glob = "0.3.3"
hmac = "0.12.1"
indicatif = "0.18.3"
rand = "0.9.2"
reed-solomon-erasure = "6.0.0"
sha2 = "0.10.9"
subtle = "2.6.1"

[dev-dependencies]
tempfile = "3.24.0"

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"

[lints.clippy]
module_inception = "allow"
