[package]
name = "sweetbyte-rs"
version = "26.1.0"
edition = "2024"
description = "A very small, very simple, yet very secure encryption tool written in rust."
license = "MIT"
authors = ["Ilham Putra Husada <hambosto@gmail.com>"]
readme = "README.md"
keywords = ["encryption", "security", "crypto", "aes", "chacha20"]
categories = ["cryptography", "command-line-utilities"]
homepage = "https://github.com/hambosto/sweetbyte-rs"
repository = "https://github.com/hambosto/sweetbyte-rs"

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.100"
argon2 = "0.5.3"
bytesize = "2.3.1"
chacha20poly1305 = "0.10.1"
clap = { version = "4.5.54", features = ["derive"] }
clap_complete = "4.5.65"
comfy-table = "7.2.2"
console = "0.16.2"
crossbeam-channel = "0.5.15"
dialoguer = "0.12.0"
fast-glob = "1.0.0"
flate2 = "1.1.8"
figlet-rs = "0.1.5"
hashbrown = "0.16.1"
hmac = "0.12.1"
indicatif = "0.18.3"
rand = { version = "0.9.2", features = ["os_rng"], default-features = false }
reed-solomon-erasure = "6.0.0"
sha2 = "0.10.9"
subtle = "2.6.1"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.24.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
