[package]
name = "sweetbyte-rs"
version = "26.1.0"
edition = "2024"
description = "A very small, very simple, yet very secure encryption tool written in rust."
license = "MIT"
authors = ["Ilham Putra Husada <hambosto@gmail.com>"]
readme = "README.md"
keywords = ["encryption", "security", "crypto", "aes", "chacha20"]
categories = ["cryptography", "command-line-utilities"]
homepage = "https://github.com/hambosto/sweetbyte-rs"
repository = "https://github.com/hambosto/sweetbyte-rs"

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.100"
argon2 = "0.5.3"
block-padding = "0.4.2"
bytesize = "2.3.1"
chacha20poly1305 = "0.10.1"
clap = { version = "4.5.56", features = [
    "derive",
    "help",
    "std",
    "usage",
], default-features = false }
comfy-table = "7.2.2"
console = "0.16.2"
fast-glob = "1.0.0"
figlet-rs = "0.1.5"
flume = "0.12.0"
hashbrown = "0.16.1"
hex = "0.4.3"
hmac = "0.12.1"
indicatif = { version = "0.18.3", features = [
    "unicode-width",
], default-features = false }
inquire = { version = "0.9.2", features = [
    "crossterm",
    "macros",
], default-features = false }
mimalloc = { version = "0.1.48", features = ["v3"], default-features = false }
rand = "0.9.2"
rayon = "1.11.0"
reed-solomon-erasure = { version = "6.0.0", features = ["simd-accel"] }
serde = { version = "1.0.228", features = [
    "derive",
    "alloc",
], default-features = false }
sha2 = "0.10.9"
sha_file_hashing = "0.1.1"
subtle = "2.6.1"
tap = "1.0.1"
tokio = { version = "1.49.0", features = [
    "io-util",
    "fs",
    "rt-multi-thread",
    "macros",
], default-features = false }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
walkdir = "2.5.0"
wincode = { version = "0.3.1", features = ["derive"] }
zstd = { version = "0.13.3", features = ["legacy", "arrays", "zdict_builder"] }

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[dev-dependencies]
tempfile = "3.24.0"
