[package]
name = "sweetbyte-rs"
version = "1.0.0"
edition = "2024"
description = "Multi-layered file encryption with error correction"
license = "MIT"
authors = ["Ilham Putra Husada <hambosto@gmail.com>"]
readme = "README.md"
keywords = ["encryption", "security", "crypto", "aes", "chacha20"]
categories = ["cryptography", "command-line-utilities"]

[dependencies]
aes-gcm = "0.10.3"
chacha20poly1305 = "0.10.1"
argon2 = "0.5.3"
hmac = "0.12.1"
sha2 = "0.10.9"
rand = "0.9.2"
reed-solomon-erasure = { version = "6.0.0", features = ["simd-accel"] }
flate2 = { version = "1.1.8", features = ["zlib-ng"], default-features = false }
clap = { version = "4.5.54", features = ["derive"] }
mimalloc = { version = "0.1.48", features = ["v3"] }
dialoguer = "0.12.0"
indicatif = "0.18.3"
console = "0.16.2"
comfy-table = "7.2.2"
crossbeam-channel = "0.5.15"
anyhow = "1.0.100"
glob = "0.3.3"
byteorder = "1.5.0"
hashbrown = "0.16.1"
rayon = "1.11.0"

[dev-dependencies]
tempfile = "3.24.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
