[package]
name = "sweetbyte-rs"
version = "26.1.0"
edition = "2024"
description = "A very small, very simple, yet very secure encryption tool written in rust."
license = "MIT"
authors = ["Ilham Putra Husada <hambosto@gmail.com>"]
readme = "README.md"
keywords = ["encryption", "security", "crypto", "aes", "chacha20"]
categories = ["cryptography", "command-line-utilities"]
homepage = "https://github.com/hambosto/sweetbyte-rs"
repository = "https://github.com/hambosto/sweetbyte-rs"

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.101"
argon2 = "0.5.3"
blake3 = "1.8.3"
block-padding = "0.4.2"
bytesize = "2.3.1"
chacha20poly1305 = "0.10.1"
clap = { version = "4.5.57", features = ["derive"] }
comfy-table = "7.2.2"
console = "0.16.2"
crc32fast = "1.5.0"
fast-glob = "1.0.0"
figlet-rs = "0.1.5"
flume = "0.12.0"
hashbrown = "0.16.1"
hex = "0.4.3"
hmac = "0.12.1"
indicatif = "0.18.3"
inquire = "0.9.3"
mimalloc = { version = "0.1.48", features = ["v3"] }
rand = { version = "0.10.0", features = ["sys_rng"] }
rayon = "1.11.0"
reed-solomon-simd = "3.1.0"
secrecy = "0.10.3"
sha2 = "0.10.9"
strum = { version = "0.27.2", features = ["derive"] }
subtle = "2.6.1"
tap = "1.0.1"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
walkdir = "2.5.0"
wincode = { version = "0.4.1", features = ["derive"] }
zstd = "0.13.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dev-dependencies]
tempfile = "3.24.0"
