[package]
name = "sweetbyte-rs"
version = "26.1.0"
edition = "2024"
description = "A very small, very simple, yet very secure encryption tool written in rust."
license = "MIT"
authors = ["Ilham Putra Husada <hambosto@gmail.com>"]
readme = "README.md"
keywords = ["encryption", "security", "crypto", "aes", "chacha20"]
categories = ["cryptography", "command-line-utilities"]
homepage = "https://github.com/hambosto/sweetbyte-rs"
repository = "https://github.com/hambosto/sweetbyte-rs"

[dependencies]
aes-gcm            = { version = "0.10.3", default-features = false, features = ["aes", "rand_core"] }
anyhow             = "1.0.101"
argon2             = { version = "0.5.3", default-features = false, features = ["alloc"] }
blake3             = { version = "1.8.3", default-features = false }
block-padding      = "0.4.2"
bytesize           = { version = "2.3.1", default-features = false }
chacha20poly1305   = "0.10.1"
clap               = { version = "4.5.60", default-features = false, features = ["derive", "std"] }
comfy-table        = "7.2.2"
console            = { version = "0.16.2", default-features = false }
crc32fast          = { version = "1.5.0", default-features = false }
fast-glob          = "1.0.0"
figlet-rs          = "0.1.5"
flume              = { version = "0.12.0", default-features = false, features = ["async"] }
hashbrown          = { version = "0.16.1", default-features = false, features = ["default-hasher"] }
hex                = { version = "0.4.3", default-features = false, features = ["alloc"] }
hmac               = "0.12.1"
indicatif          = { version = "0.18.4", default-features = false }
inquire            = { version = "0.9.3", default-features = false, features = ["crossterm", "macros"] }
mimalloc           = { version = "0.1.48", features = ["v3"] }
rand               = { version = "0.10.0", default-features = false, features = ["sys_rng"] }
rayon              = "1.11.0"
reed-solomon-simd  = { version = "3.1.0", default-features = false }
secrecy            = "0.10.3"
sha2               = "0.10.9"
strum              = { version = "0.28.0", default-features = false, features = ["derive"] }
subtle             = { version = "2.6.1", default-features = false, features = ["std"] }
tap                = "1.0.1"
tokio              = { version = "1.49.0", default-features = false, features = ["fs", "io-std", "io-util", "macros", "rt-multi-thread"] }
tracing            = { version = "0.1.44", default-features = false, features = ["tracing-attributes"] }
tracing-subscriber = { version = "0.3.22", default-features = false, features = ["ansi"] }
walkdir            = "2.5.0"
wincode            = { version = "0.4.4", default-features = false, features = ["alloc", "derive"] }
zstd               = { version = "0.13.3", default-features = false, features = ["thin"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dev-dependencies]
tempfile = "3.24.0"

[lints.clippy]
all = "warn"
pedantic = "warn"
